# Funding options for this project

# Original project funding
# See: https://github.com/google-gemini/gemini-cli

# This fork is maintained independently by Ibrahim4594
# If you find the Windows enhancements helpful, consider:
# - Starring the repository ⭐
# - Sharing with other Windows developers
# - Contributing improvements

github: [google-gemini]
